name: "Publish"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run checks

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Set up Python environment
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
      - name: Run type checks
        run: make typecheck

  release-please:
    name: Execute release chores

    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: derdiedas
